name: rebootibm
on:
  #schedule:
    #- cron: 10 22 * * 6   想要每周自动重启 就取消注释掉此项   
  watch:
    types: started      
jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source cf
      run: |
        cd /home/runner
        curl -LO https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.52.0/cf-cli_6.52.0_linux_x86-64.tgz
        tar zxvf cf-cli_6.52.0_linux_x86-64.tgz
        chmod +x ./cf
        sudo mv ./cf /usr/bin/cf
    - name: cf login ibm
      run: |
        cf api api.us-south.cf.cloud.ibm.com
        cf login -u ${{ secrets.ibmuser }} -p ${{ secrets.ibmpasswd }}
    - name: Restart IBM Cloud
      run: |
        #查看运行的应用
        cf apps
        #获取应用名称
        ibmapp=$(cf apps |grep h |awk '{print $1}')
        #重启应用
        cf restart $ibmapp
        #注销登录
        cf logout
