name: ibm-reboot
on:
  schedule:
    - cron: 10 22 * * 6
jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        cd /home/runner
        wget https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/1.1.0/binaries/IBM_Cloud_CLI_1.1.0_linux_amd64.tgz
        tar zxvf IBM_Cloud_CLI_1.1.0_linux_amd64.tgz
    - name: go kaishi
      run: |
        cd /home/runner/IBM_Cloud_CLI
        echo 7 | /home/runner/IBM_Cloud_CLI/ibmcloud login -u ${{ secrets.ibmuser2 }} -p ${{ secrets.ibmpasswd }}
        /home/runner/IBM_Cloud_CLI/ibmcloud target --cf
        /home/runner/IBM_Cloud_CLI/ibmcloud cf install
        /home/runner/IBM_Cloud_CLI/ibmcloud cf restart yanzi
